#!/bin/bash

trap '' PIPE
{
  #
  # start the server we proxy to
  #
  _PROXYTO=http://localhost:3003 _APPPORT=1337 node app.js <&3 >&4 |
  #
  # real life this would just be groundhog
  #
  DEBUG="groundhog:*" ../bin/groundhog $* <&3 >&4 |
  #
  # run our tests
  #
  _PROXYTO=http://localhost:3003 _APPPORT=1337 node test/index.js <&3 >&4
} 3<&0 4>&1
